# Zellij Mane 6 theme generator.
# Writes KDL theme files under ~/.config/zellij/themes/ (or -OutDir).
# Activate by adding `theme "pony-<name>"` to ~/.config/zellij/config.kdl.
#
# Examples:
#   zellij-pony.ps1 -Pony twilight              # write one
#   zellij-pony.ps1 -All                        # write all 6
#   zellij-pony.ps1 -List
#   zellij-pony.ps1 -Pony pinkie -OutDir ./out  # custom dir

param(
  [string]$Pony,
  [switch]$All,
  [switch]$List,
  [string]$OutDir
)

# Zellij config location differs by platform.
if (-not $OutDir) {
  if ($IsWindows -or $env:OS -eq 'Windows_NT') {
    $OutDir = Join-Path $env:APPDATA 'Zellij\config\themes'
  } else {
    $OutDir = Join-Path $HOME '.config/zellij/themes'
  }
}

# Palettes derived from the starship pony palettes, extended to zellij's 11 slots
# (fg, bg, black, red, green, yellow, blue, magenta, cyan, white, orange).
# Each pony's bg matches its complementary backdrop from preview.ps1.
$Palettes = @{
  twilight = @{
    fg='#f5e6ff'; bg='#0a0414'; black='#1a1033'; white='#f5e6ff'
    red='#f5a9d0'; green='#6bcf7f'; yellow='#ffd93d'
    blue='#6cb4ee'; magenta='#b48ce8'; cyan='#7fb8d4'; orange='#f0a04b'
  }
  rainbow = @{
    fg='#ffffff'; bg='#0a1420'; black='#0d1b2a'; white='#ffffff'
    red='#ff6b6b'; green='#6bcf7f'; yellow='#ffd93d'
    blue='#5dadec'; magenta='#b388eb'; cyan='#89cff0'; orange='#ffa94d'
  }
  pinkie = @{
    fg='#fde2f3'; bg='#1a0a14'; black='#2d1424'; white='#fde2f3'
    red='#e85ba8'; green='#94c973'; yellow='#f9d56e'
    blue='#6cb4ee'; magenta='#f5a9d0'; cyan='#89cff0'; orange='#f0a04b'
  }
  applejack = @{
    fg='#fde8c8'; bg='#150a06'; black='#2a1810'; white='#fde8c8'
    red='#d97706'; green='#4a8c3a'; yellow='#f5d068'
    blue='#6cb4ee'; magenta='#b48ce8'; cyan='#7fb8d4'; orange='#f0a04b'
  }
  rarity = @{
    fg='#f5edff'; bg='#0f0a1c'; black='#1a1530'; white='#f5edff'
    red='#f5a9d0'; green='#94c973'; yellow='#f0d878'
    blue='#7fb8d4'; magenta='#9d7ec9'; cyan='#d4c0ed'; orange='#f0a04b'
  }
  fluttershy = @{
    fg='#fff7d6'; bg='#1a140a'; black='#2d2418'; white='#fff7d6'
    red='#f4a8c8'; green='#94c973'; yellow='#fde9a4'
    blue='#6cb4ee'; magenta='#d4b85a'; cyan='#89cff0'; orange='#f0a04b'
  }
}

if ($List) {
  Write-Host "Ponies: $($Palettes.Keys -join ', ')"
  return
}

function ToKdl([string]$name, $p) {
@"
// Generated by zellij-pony.ps1
// Activate via:  theme "pony-$name"  in ~/.config/zellij/config.kdl
themes {
    pony-$name {
        fg              "$($p.fg)"
        bg              "$($p.bg)"
        black           "$($p.black)"
        red             "$($p.red)"
        green           "$($p.green)"
        yellow          "$($p.yellow)"
        blue            "$($p.blue)"
        magenta         "$($p.magenta)"
        cyan            "$($p.cyan)"
        white           "$($p.white)"
        orange          "$($p.orange)"
    }
}
"@
}

function WriteOne([string]$name) {
  $out = Join-Path $OutDir "pony-$name.kdl"
  $kdl = ToKdl $name $Palettes[$name]
  [System.IO.File]::WriteAllText($out, $kdl, [System.Text.UTF8Encoding]::new($false))
  Write-Host "Wrote $out"
}

New-Item -ItemType Directory -Force $OutDir | Out-Null

if ($All) {
  foreach ($name in $Palettes.Keys) { WriteOne $name }
  Write-Host ""
  Write-Host "Add one of these to ~/.config/zellij/config.kdl:"
  foreach ($name in $Palettes.Keys) { Write-Host "  theme `"pony-$name`"" }
  return
}

if (-not $Pony) { Write-Error "Specify -Pony or -All. Try -List."; return }
if (-not $Palettes.ContainsKey($Pony)) { Write-Error "Unknown pony '$Pony'. Try -List."; return }
WriteOne $Pony
Write-Host ""
Write-Host "Activate by adding to ~/.config/zellij/config.kdl:"
Write-Host "  theme `"pony-$Pony`""
